// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc5124.robot2020.subsystems;

import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj.controller.PIDController;
import edu.wpi.first.wpilibj.PWMVictorSPX;

/**
 * 
 */
public class Intake implements Subsystem {

private PWMVictorSPX armSpeedController;
private PIDController deployArmPIDController;
private PWMVictorSPX rollerSpeedController;

    public Intake() {

        armSpeedController = new PWMVictorSPX(8);
        armSpeedController.setInverted(false);

        // need to add a REV through-bore encoder for the PID controller
        
        deployArmPIDController = new PIDController(1.0, 0.0, 0.0, 0.0);
        deployArmPIDController.setTolerance(0.2);
                
        rollerSpeedController = new PWMVictorSPX(9);
        rollerSpeedController.setInverted(false);

    }



    @Override
    public void periodic() {
        // Put code here to be run every loop

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void in() {
        rollerSpeedController.set(1.0);
    }

    public void out() {
        rollerSpeedController.set(-1.0);
    }

    public void stop() {
        rollerSpeedController.set(0.0);
    }

    public void deploy() {
        deployArmPIDController.setSetpoint(1.0);
    }

    public void retract() {
        deployArmPIDController.setSetpoint(0.0);
    }
}

