// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc5124.robot2020.subsystems;


import frc.robot.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj.PWMVictorSPX;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.SpeedControllerGroup;


/**
 *
 */
public class Loader extends Subsystem {
    private PWMVictorSPX topBeltSpeedController;
    private PWMVictorSPX bottomBeltSpeedController;
    private SpeedControllerGroup beltSpeedControllerGroup;

    
    public Loader() {
        topBeltSpeedController = new PWMVictorSPX(5);
        topBeltSpeedController.setInverted(false);
        
        bottomBeltSpeedController = new PWMVictorSPX(4);
        bottomBeltSpeedController.setInverted(true);
        
        beltSpeedControllerGroup = new SpeedControllerGroup(topBeltSpeedController, bottomBeltSpeedController  );


    }


    @Override
    public void periodic() {
        // Put code here to be run every loop

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

